### PR TITLE
Uppercase and lowercase string enums behaviour updated

### PR DESCRIPTION
**Pull request by emakarov**
Copy of https://github.com/Infinidat/infi.clickhouse_orm/pull/157 for develop branch, as requested

### CODE REVIEW

**Comment by ayoshi** [comment]
Thank you! merged

**Comment by emakarov** [comment]
hi @ayoshi is there any plans to make new pypi release with this PR included?

**Comment by ayoshi** [comment]
Yes, it will take some time, but this fix is definitely a part of a next version, though we don't have a due date for it.

**Comment by emakarov** [comment]
@ayoshi thanks! appreciate you make it sooner than later :)

**Comment by emakarov** [comment]
hi @ayoshi 
could you update on this? pypi is not renewed anymore? Project looks like abandoned already with such delayed releases. 
Are you going to support public releases in future?

**Pull request merged**
