### PR TITLE
Revert "Uppercase and lowercase string enums behaviour updated."

### PR DESCRIPTION
**Pull request by ayoshi**
Reverts Infinidat/infi.clickhouse_orm#157 - should be merged into develop

### CODE REVIEW

**Comment by emakarov** [comment]
hi @ayoshi so PR was reverted, what is the reason of revert?

**Comment by ayoshi** [comment]
@emakarov sorry, my bad - I merged it into master when it should have been merged into develop. could you please reopen the PR against develop?

**Comment by emakarov** [comment]
@ayoshi currently when I try to create PR - "Infinidat:develop is up to date with all commits from emakarov:case_sensitive_strenums"
Did you merge it yourself already?

**Comment by ayoshi** [comment]
I think it’s because of revert, the old commit is already in both branches together with revert - can you reapply the change in the new commit after rebasing both branches? I apologize, all this is because the original PR was against master, so after applying I needed to rebase both branches

**Comment by emakarov** [comment]
created new PR https://github.com/Infinidat/infi.clickhouse_orm/pull/161

**Pull request merged**
