### PR TITLE
Improve testing, change Model._fields, Distributed engine

### PR DESCRIPTION
**Pull request by tsionyx**
This update can potentially break the old code which uses `Model._fields` or `Model._writable_fields` but I think that's not so bad since they are for class internal usage (started with an underscore). However `Model._fields` represented as an `OrderedDict` is way more convenient than the previous list of pairs and also preserves order.

Also I could not find a way to install `tox` automatically as I do not have experience with buildout, but tox really simplifies testing for py2 and py3 (I use this library in a cross-versioned project).

The new `ServerError` exception is backward compatible with `DatabaseException` so it should not be troubles with it.

And Distributed engine can be helpful for those who want to use clustered environment.

### CODE REVIEW

**Comment by ishirav** [comment]
Hi,

Sorry for the long delay.

That's a pretty impressive pull request! A couple of questions:
1. What is the idea behind ServerError? Is it just a way to parse the error message returned by ClickHouse?
2. What is gained by converting _fields to an OrderedDict? Was this change required in order to implement some specific functionality?

Thanks!

**Comment by tsionyx** [comment]
Hi!
1. Yeah, it's just for parsing. My app sometimes has to check what was the cause of the error and the error codes is already there. So I think it would be great to have them parsed.
2. No, it's just refactoring that give nothing specific, but improved readability (yes, it's subjective):
 a) it's easier to access to individual fields (just by doing `_fields[field_name]`), e.g when you need the type of the field and you have just a name. 
  b) it's easier to iterate:
       `for field in self._fields:` iterates over the field names
       `list(self._fields)` gets the list of field names.
  Of course I thought of simple `dict` at first, but we need to save the order of fields, so `OrderedDict` is here, which, as I suppose, perfectly fits such a use case.

**Comment by ishirav** [comment]
Awesome work as usual!
I really want to merge these into the develop branch, but I'm not too happy about the flake8 changes. It's a matter of personal taste of course, but I feel that it's unnecessarily restrictive (especially re whitespace and line wrapping). So I suggest to revert the last commit, and then go over each warning emitted by flake8 and decide together whether to ignore it or keep it.

**Comment by tsionyx** [comment]
I just removed that commit from the develop branch history to ease merging (the changes left in flake8 branch).

**Pull request closed without merging**
