### PR TITLE
Added MaterializedField and AliasField

### PR DESCRIPTION
**Pull request by M1hacka**

### CODE REVIEW

**Comment by ishirav** [comment]
Hi,

I looked at your work and I have a question. Why did you choose to model this feature as two new types of fields, whereas in ClickHouse these are not fields but options that can be applied to each field?

What I mean is, why not allow something like this:
username = StringField(alias='name')
or:
mat_int = Int32Field(materialized='abs(int_field)')

Field classes are mapped to datatypes (e.g. string field, int field etc.) both in ClickHouse and infi.clickhouse_orm. Alias and materialized are not datatypes, but rather field options (just like default value). So it's better to model them as such.

**Comment by M1hacka** [comment]
I thought about this, but these field options are not like default. These fields both are not stored in the database, they can't be inserted or got over *. So it's not string field - it is only acting alike. If I create StringField, I expect it work as full function string field

**Comment by M1hacka** [comment]
I thought about this, but these field options are not like default. These fields both are not stored in the database, they can't be inserted or got over *. So it's not string field - it is only acting alike. If I create StringField, I expect it works as full function string field

**Comment by ishirav** [comment]
I think we should try to model the fields similar to they way they are defined in ClickHouse, so that someone who reads the ClickHouse documentation and then uses the ORM sees the same terminology and concepts in both places. If the designers of the database thought that alias/materialized is a field property (and not a different type of field), we should do the same. It's probably not a big change in the code... if you don't have time to do it, I can try to do it myself.

**Comment by M1hacka** [comment]
I've committed version, rewritten with parameters usage.

**Comment by ishirav** [comment]
Great! I'll go over it.

**Comment by M1hacka** [comment]
Hey, I'm looking forward for any reviews =)
I've also made next commits on working with partitions (drop, attach, detach, freeze, get), but I don't want committing it here (another pull request). It's not fully done as I want (nevertheless, it's working), but I'm not sure, I'm going to improve it in a short time (it suits my project purposes)

**Comment by ishirav** [comment]
I'm working on integrating your code - so far it looks great.

**Pull request merged**
