### PR TITLE
Added support for Buffer engine

### PR DESCRIPTION
**Pull request by emakarov**
- Added support for Buffer engine
- Added documentation with examples

### CODE REVIEW

**Comment by ishirav** [comment]
Hi,

The pull request looks good. Could you kindly add a test or two under /tests ?

Thanks!

**Comment by emakarov** [comment]
I'm trying tests now locally. How did you manage to create database in Clickhouse with name test-db ? I can't create DB with "-" sign in the middle

**Comment by ishirav** [comment]
You need to surround it with backticks: `test-db`

**Comment by emakarov** [comment]
Added minimal test and actually that helped to find bug with these database names

**Pull request merged**
